### ISSUE TITLE
Java 8 and Clojure 1.6.0 required

### ISSUE THREAD

**Issue by lsh-0** [solicode/clj-thrust#1]
I had some minor issues installing clj-thrust so I'll just document them here quickly. 

Java 8 is required. I was getting this exception attempting to run the code in the README

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: clj_thrust/RpcWriter : Unsupported major.minor version 52.0
```

Clojure 1.6.0 is required. After upgrading to Java 8, I was getting:

```
Exception in thread "main" java.lang.RuntimeException: Unable to resolve symbol: some? in this context, compiling:(clj_thrust/core.clj:25:34)
```

I'm on an older version of Leiningen I guess that is still using Clojure 1.5

**Comment by solicode** [comment]
Thanks for letting me know. This is an oversight on my part. I didn't realize this would happen, but it makes sense now considering this is a mixed Clojure/Java project.

I see no reason for this project to force Java 8 (or Clojure 1.6 for that matter), so I'll look into fixing this.

**Comment by solicode** [comment]
Alright, this should be taken care of now.
